### ISSUE TITLE
GHC 8.4 support

### ISSUE THREAD

**Issue by expipiplus1** [DavidM-D/indexed-list-literals#1]
This is currently blocked on OneTuple missing a Semigroup instance. I've emailed John Dorsey about this and will update here when he responds.

**Comment by gwils** [comment]
If John Dorsey does not respond, you could move to the competing package `Only`, which supports GHC 8.4

**Comment by expipiplus1** [comment]
No response from John sadly.

**Comment by DavidM-D** [comment]
Apologies for the slow response, I didn't receive a notification for this issue. Feel free to email directly if something like this happens again.

**Comment by expipiplus1** [comment]
Thanks!
