### ISSUE TITLE
It would be nice to have fromList or toTuple

### ISSUE THREAD

**Issue by expipiplus1** [DavidM-D/indexed-list-literals#4]
title

**Comment by DavidM-D** [comment]
I can do it at the weekend if you like

**Comment by expipiplus1** [comment]
Sure thanks! No urgent rush though :)

**Comment by DavidM-D** [comment]
Fixed in https://github.com/DavidM-D/indexed-list-literals/pull/5

**Comment by expipiplus1** [comment]
Thanks!
