### ISSUE TITLE
Base version bound too restrictive (GHC 8.8)

### ISSUE THREAD

**Issue by kozross** [DavidM-D/indexed-list-literals#9]
We spotted this as part of [this ``vector-sized`` issue][1]. In our particular case, the version bound doesn't seem to matter, as with ``--allow-newer``, we build fine. Would it be possible to raise the version bound to accommodate use of GHC 8.8?

[1]: https://github.com/expipiplus1/vector-sized/issues/78

**Comment by gwils** [comment]
I've made a hackage metadata revision to version 0.2.1.2 to allow building with GHC 8.8

**Comment by kozross** [comment]
Thanks @gwils! Will close this now.
